version: '3'
services:
  db:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
      # NOTE: You will need to update config/database.yml file as well with the value for POSTGRES_USER as well
      - POSTGRES_USER=postgres
    volumes:
      -  postgres-data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash docker_bootstrap.sh
    environment:
        DB_HOST: db
        RACK_ENV: development
        RAILS_ENV: development
        PORT: 3000
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data-volume:
    external: true